[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m pytest_operator.plugin:plugin.py:734 Connecting to existing model concierge-lxd:testing on unspecified cloud
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHSession received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHTunneler received from the controller
[33mWARNING [0m juju.client.connection:connection.py:858 unexpected facade SSHServer received from the controller
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:34 Deploying all the applications
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-test-app-73
[32mINFO    [0m juju.model:model.py:2284 Deploying ch:amd64/jammy/mysql-370
[32mINFO    [0m juju.model:model.py:2284 Deploying local:mysql-router-0
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:64 Relating mysqlrouter with mysql-test-app
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:81 Relating mysqlrouter with mysql
[33mWARNING [0m juju.model:model.py:1666 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:97 Removing the cron file
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:102 Stopping any running logrotate jobs
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:105 Removing existing archive directory
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:112 Writing some data mysqlrouter log file
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:116 Ensuring only log files exist
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:127 Executing logrotate
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:143 Ensuring log files and archive directories exist
[32mINFO    [0m integration.test_log_rotation:test_log_rotation.py:157 Ensuring log files was rotated
[32mINFO    [0m pytest_operator.plugin:plugin.py:862 Model status:

Model    Controller     Cloud/Region         Version  SLA          Timestamp
testing  concierge-lxd  localhost/localhost  3.6.5    unsupported  01:44:07Z

App             Version          Status  Scale  Charm           Channel      Rev  Exposed  Message
mysql           8.0.41-0ubun...  active      1  mysql           8.0/edge     370  no       
mysql-router    8.0.41-0ubun...  active      1  mysql-router                   0  no       
mysql-test-app  0.0.2            active      1  mysql-test-app  latest/edge   73  no       

Unit               Workload  Agent  Machine  Public address  Ports           Message
mysql-test-app/0*  active    idle   0        10.230.70.47                    
  mysql-router/0*  active    idle            10.230.70.47                    
mysql/0*           active    idle   1        10.230.70.241   3306,33060/tcp  Primary

Machine  State    Address        Inst id        Base          AZ  Message
0        started  10.230.70.47   juju-43efae-0  ubuntu@22.04      Running
1        started  10.230.70.241  juju-43efae-1  ubuntu@22.04      Running

[32mINFO    [0m pytest_operator.plugin:plugin.py:868 Juju error logs:

machine-0: 01:41:38 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-0: 01:41:38 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-test-app-0: 01:41:38 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-router-0: 01:41:43 ERROR juju.worker.meterstatus error running "meter-status-changed": exit status 1
machine-1: 01:42:41 ERROR juju.worker.dependency "kvm-container-provisioner" manifold worker returned unexpected error: container types not yet available
machine-1: 01:42:41 ERROR juju.worker.dependency "lxd-container-provisioner" manifold worker returned unexpected error: container types not yet available
unit-mysql-0: 01:42:41 ERROR juju.worker.meterstatus error running "meter-status-changed": charm missing from disk
unit-mysql-0: 01:43:25 ERROR unit.mysql/0.juju-log ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock' (2)
unit-mysql-0: 01:43:25 ERROR unit.mysql/0.juju-log Failed to execute MySQL cli command
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/mysql/v0/mysql.py", line 3363, in check_mysqlcli_connection
    self._run_mysqlcli_script(
  File "/var/lib/juju/agents/unit-mysql-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1065, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 855, in _run_mysqlcli_script
    raise MySQLClientError
charms.mysql.v0.mysql.MySQLClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-0/charm/src/mysql_vm_helpers.py", line 860, in _run_mysqlcli_script
    stdout = subprocess.check_output(command, timeout=timeout, text=True)
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['charmed-mysql.mysql', '-u', 'root', '-N', '-B', '--socket=/var/snap/charmed-mysql/common/var/run/mysqld/mysqld.sock', '-e', 'SELECT 1']' returned non-zero exit status 1.
unit-mysql-0: 01:43:25 ERROR unit.mysql/0.juju-log Failed to connect to MySQL with mysqlcli with default root user

[32mINFO    [0m pytest_operator.plugin:plugin.py:947 Forgetting model main...